### ISSUE TITLE
Graphcool Server Code?

### ISSUE THREAD

**Issue by idkjs** [johnpaulada/life-skill-stats#1]
Hey boss. Thanks for sharing. Would you mind sharing the prisma server code?

Thanks again!

**Comment by johnpaulada** [comment]
Hi! Yeah sorry I just wrote it on the server. I'll try extracting the schema one of these days. Thanks!

**Comment by idkjs** [comment]
Already did that. https://gist.github.com/idkjs/c227b3367a24fd0ed2ce2fc5d52484b5. Figured I would ask before going through it for your types. Thanks.
